### PR TITLE
(4/4) Sudoku Improvements

### PR DESCRIPTION
**Pull request by Utkub24**
takes forward #13

## What are we doing with this PR?

Add QOL improvements to Sudoku controls and page.
- Highlight related tiles.

## Screenshots

image

### CODE REVIEW

**Review by lucashlz — APPROVED** [review]

**Comment by lucashlz** [comment]
how do u access the page ?

**Comment by Utkub24** [comment]
> how do u access the page ?

It's at `/puzzle/sudoku`

You can go there directly or press 'solve' on the `/puzzle/select` page

**Comment by lucashlz** [comment]
Screenshot from 2024-12-27 02-01-28
I have this when I go on /puzzle/sudoku

Also I can't access /puzzle/select

**Comment by Utkub24** [comment]
> Screenshot from 2024-12-27 02-01-28
> 
> I have this when I go on /puzzle/sudoku
> 
> 
> 
> Also I can't access /puzzle/select
> 
> 

Oh, that's weird. It seems like tailwind isn't working properly.
You should run `pnpm install` if you haven't already, just in case.


Which error do you get when you access /puzzle/select ?

**Pull request merged**
